// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX0NesEpBtzCBarSx0VQ6q9_35wgcSjIo',
    appId: '1:840520942846:web:5ea916bcbd11e5e0a2d1af',
    messagingSenderId: '840520942846',
    projectId: 'tvde-app',
    authDomain: 'tvde-app.firebaseapp.com',
    storageBucket: 'tvde-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH1ty1y0Kr2kwBagNnUSM2UMaVMvQjKU0',
    appId: '1:840520942846:ios:0075ef21a8208c61a2d1af',
    messagingSenderId: '840520942846',
    projectId: 'tvde-app',
    storageBucket: 'tvde-app.firebasestorage.app',
    iosBundleId: 'pt.1977.ap1977',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH1ty1y0Kr2kwBagNnUSM2UMaVMvQjKU0',
    appId: '1:840520942846:ios:0075ef21a8208c61a2d1af',
    messagingSenderId: '840520942846',
    projectId: 'tvde-app',
    storageBucket: 'tvde-app.firebasestorage.app',
    iosBundleId: 'pt.1977.ap1977',
  );

}